### ISSUE TITLE
The 4000er converter from SMA is not a SB type

### ISSUE THREAD

**Issue by deHarro** [mincequi/ElsewhereEdge#2]
Hi @mincequi ,

in the readme, do you reference my Sunny Island battery converter as [SB]4000TL-21?
If so, please be informed, that it is of type "Sunny Island SI 4.4M-11" (other naming scheme).

Beyond that, it seems to not deliver any power data, at least no min and max values.
Perhaps the Sunny **Island** data are named different from the Sunny **Boy** devices?

**Comment by mincequi** [comment]
Thanks, but with SB4000TL-21 i actually mean SB4000TL-21 ;)

The Sunny Island will be separately listed, once it is supported.
So far, i do not know, why there is no data. You could get a modbus client and check if you can obtain data (via sunspec registers or from the SMA registers).

**Comment by deHarro** [comment]
Ok, thanks!
