### ISSUE TITLE
Goodwe Inverter GW3648D-ES

### ISSUE THREAD

**Issue by Schhlimmerfinger** [mincequi/ElsewhereEdge#4]
Hi Manuel, 
are you planing to ad the config file and influx DB 2.x capability in your tool?
I would be very intersted.
Thx

Alex

**Comment by mincequi** [comment]
Hi Alex,
the config file won't be a big issue (as well as the Debian package).
However, I have my doubts about InfluxDB 2.x. The compatibility mode might be a workaround: https://docs.influxdata.com/influxdb/v2.6/reference/api/influxdb-1x/

BR
Manuel
